---
- name: Deploy Docker Image to Container
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      service:
        name: jayparekhiiitb/spe_mini_project
        shell: docker pull jayparekhiiitb/spe_mini_project

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: SPE_mini_project
        shell: docker run -it -d jayparekhiiitb/spe_mini_project
