---
- name: Deploy Docker Image to Container
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      shell: docker pull jayparekhiiitb/spe_mini_project:latest

    - name: Create & Start Calculator Docker Container
      shell: docker run -it -d jayparekhiiitb/spe_mini_project